import { sql } from 'drizzle-orm'
import {
  bigint,
  boolean,
  check,
  foreignKey,
  index,
  integer,
  jsonb,
  pgTable,
  primaryKey,
  real,
  smallint,
  text,
  timestamp,
  uniqueIndex,
  varchar,
} from 'drizzle-orm/pg-core'

const timestamps = {
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}

export const users = pgTable('users', {
  firebaseUid: varchar('firebase_uid', { length: 128 }).primaryKey(),
  email: varchar('email', { length: 200 }),
  displayName: varchar('display_name', { length: 100 }),
  photoUrl: text('photo_url'),
  status: text('status').notNull().default('active'),
  ...timestamps,
}, table => [
  check('users_status_check', sql`${table.status} in ('active', 'disabled', 'deleted')`),
  uniqueIndex('users_email_unique').on(sql`lower(${table.email})`).where(sql`${table.email} is not null`),
  index('users_status_idx').on(table.status),
])

export const admins = pgTable('admins', {
  userId: varchar('user_id', { length: 128 }).primaryKey().references(() => users.firebaseUid, { onDelete: 'restrict' }),
  label: varchar('label', { length: 200 }),
  emailSnapshot: varchar('email_snapshot', { length: 200 }),
  grantedBy: varchar('granted_by', { length: 128 }).references(() => users.firebaseUid, { onDelete: 'restrict' }),
  grantSource: text('grant_source').notNull().default('admin'),
  grantedAt: timestamp('granted_at', { withTimezone: true }).notNull().defaultNow(),
  revokedBy: varchar('revoked_by', { length: 128 }).references(() => users.firebaseUid, { onDelete: 'restrict' }),
  revokedAt: timestamp('revoked_at', { withTimezone: true }),
}, table => [
  check('admins_grant_source_check', sql`${table.grantSource} in ('bootstrap', 'admin', 'migration')`),
  index('admins_active_idx').on(table.userId).where(sql`${table.revokedAt} is null`),
  index('admins_granted_at_idx').on(table.grantedAt),
])

export const branches = pgTable('branches', {
  id: varchar('id', { length: 128 }).primaryKey(),
  name: varchar('name', { length: 100 }).notNull(),
  normalizedName: varchar('normalized_name', { length: 100 }).notNull(),
  type: text('type'),
  status: text('status').notNull().default('active'),
  createdBy: varchar('created_by', { length: 128 }).references(() => users.firebaseUid, { onDelete: 'restrict' }),
  ...timestamps,
}, table => [
  check('branches_id_check', sql`${table.id} ~ '^[a-zA-Z0-9_-]+$'`),
  check('branches_type_check', sql`${table.type} is null or ${table.type} in ('KC', 'KCP')`),
  check('branches_status_check', sql`${table.status} in ('active', 'archived')`),
  uniqueIndex('branches_normalized_name_unique').on(table.normalizedName),
  index('branches_status_name_idx').on(table.status, table.name),
])

export const memberships = pgTable('memberships', {
  userId: varchar('user_id', { length: 128 }).primaryKey().references(() => users.firebaseUid, { onDelete: 'restrict' }),
  branchId: varchar('branch_id', { length: 128 }).notNull().references(() => branches.id, { onDelete: 'restrict' }),
  selectedAt: timestamp('selected_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  updatedBy: varchar('updated_by', { length: 128 }).references(() => users.firebaseUid, { onDelete: 'restrict' }),
}, table => [index('memberships_branch_idx').on(table.branchId)])

export const personas = pgTable('personas', {
  id: varchar('id', { length: 128 }).primaryKey(),
  status: text('status').notNull().default('approved'),
  currentVersion: integer('current_version').notNull().default(1),
  createdBy: varchar('created_by', { length: 128 }).references(() => users.firebaseUid, { onDelete: 'restrict' }),
  ...timestamps,
}, table => [
  check('personas_id_check', sql`${table.id} ~ '^[a-zA-Z0-9_-]+$'`),
  check('personas_status_check', sql`${table.status} in ('approved', 'archived')`),
  check('personas_current_version_check', sql`${table.currentVersion} >= 1`),
  index('personas_status_updated_idx').on(table.status, table.updatedAt),
])

export const personaSubmissions = pgTable('persona_submissions', {
  id: varchar('id', { length: 128 }).primaryKey(),
  status: text('status').notNull().default('pending'),
  creatorUserId: varchar('creator_user_id', { length: 128 }).notNull().references(() => users.firebaseUid, { onDelete: 'restrict' }),
  creatorNameSnapshot: varchar('creator_name_snapshot', { length: 100 }).notNull(),
  creatorEmailSnapshot: varchar('creator_email_snapshot', { length: 200 }).notNull(),
  creatorBranchId: varchar('creator_branch_id', { length: 128 }).notNull().references(() => branches.id, { onDelete: 'restrict' }),
  creatorBranchNameSnapshot: varchar('creator_branch_name_snapshot', { length: 100 }).notNull(),
  personaPayload: jsonb('persona_payload').$type<Record<string, unknown>>().notNull(),
  targetPersonaId: varchar('target_persona_id', { length: 128 }).references(() => personas.id, { onDelete: 'restrict' }),
  previousSubmissionId: varchar('previous_submission_id', { length: 128 }),
  submittedAt: timestamp('submitted_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  reviewedAt: timestamp('reviewed_at', { withTimezone: true }),
  reviewedByUserId: varchar('reviewed_by_user_id', { length: 128 }).references(() => users.firebaseUid, { onDelete: 'restrict' }),
  reviewedByNameSnapshot: varchar('reviewed_by_name_snapshot', { length: 100 }),
  rejectionReason: varchar('rejection_reason', { length: 1000 }),
}, table => [
  check('persona_submissions_id_check', sql`${table.id} ~ '^[a-zA-Z0-9_-]+$'`),
  check('persona_submissions_status_check', sql`${table.status} in ('pending', 'approved', 'rejected')`),
  check('persona_submissions_previous_check', sql`${table.previousSubmissionId} is null or ${table.previousSubmissionId} <> ${table.id}`),
  check('persona_submissions_public_payload_check', sql`not (${table.personaPayload} ?| array['hiddenInstructions', 'personaKnowledge', 'personaUnknowns'])`),
  foreignKey({ columns: [table.previousSubmissionId], foreignColumns: [table.id], name: 'persona_submissions_previous_fk' }).onDelete('restrict'),
  index('persona_submissions_creator_idx').on(table.creatorUserId, table.submittedAt),
  index('persona_submissions_status_idx').on(table.status, table.submittedAt),
  index('persona_submissions_target_idx').on(table.targetPersonaId, table.submittedAt),
  index('persona_submissions_branch_idx').on(table.creatorBranchId),
])

export const personaVersions = pgTable('persona_versions', {
  personaId: varchar('persona_id', { length: 128 }).notNull().references(() => personas.id, { onDelete: 'cascade' }),
  version: integer('version').notNull(),
  sourceSubmissionId: varchar('source_submission_id', { length: 128 }).references(() => personaSubmissions.id, { onDelete: 'restrict' }),
  creatorUserId: varchar('creator_user_id', { length: 128 }).references(() => users.firebaseUid, { onDelete: 'restrict' }),
  creatorNameSnapshot: varchar('creator_name_snapshot', { length: 100 }),
  creatorEmailSnapshot: varchar('creator_email_snapshot', { length: 200 }),
  creatorBranchId: varchar('creator_branch_id', { length: 128 }).references(() => branches.id, { onDelete: 'restrict' }),
  creatorBranchNameSnapshot: varchar('creator_branch_name_snapshot', { length: 100 }),
  approvedBy: varchar('approved_by', { length: 128 }).references(() => users.firebaseUid, { onDelete: 'restrict' }),
  approvedAt: timestamp('approved_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  name: varchar('name', { length: 100 }).notNull(),
  gender: text('gender').notNull(),
  age: smallint('age').notNull(),
  occupation: varchar('occupation', { length: 200 }).notNull().default(''),
  familyStatus: varchar('family_status', { length: 200 }).notNull().default(''),
  incomeRange: varchar('income_range', { length: 200 }).notNull().default(''),
  backgroundStory: text('background_story').notNull().default(''),
  currentSituation: text('current_situation').notNull().default(''),
  goals: text('goals').notNull().default(''),
  painPoints: text('pain_points').notNull().default(''),
  motivations: text('motivations').notNull().default(''),
  personality: varchar('personality', { length: 100 }).notNull(),
  emotionalLevel: smallint('emotional_level').notNull(),
  aggressiveness: smallint('aggressiveness').notNull(),
  patience: smallint('patience').notNull(),
  trustLevel: smallint('trust_level').notNull(),
  curiosityLevel: smallint('curiosity_level').notNull(),
  speechStyle: varchar('speech_style', { length: 100 }).notNull(),
  tone: varchar('tone', { length: 100 }).notNull(),
  formality: varchar('formality', { length: 100 }).notNull(),
  speakingSpeed: varchar('speaking_speed', { length: 100 }).notNull(),
  commonPhrases: text('common_phrases').notNull().default(''),
  commonObjections: text('common_objections').notNull().default(''),
  triggerConditions: text('trigger_conditions').notNull().default(''),
  escalationBehavior: text('escalation_behavior').notNull().default(''),
  legacyData: jsonb('legacy_data').$type<Record<string, unknown>>(),
}, table => [
  primaryKey({ columns: [table.personaId, table.version] }),
  check('persona_versions_version_check', sql`${table.version} >= 1`),
  check('persona_versions_gender_check', sql`${table.gender} in ('Pria', 'Wanita')`),
  check('persona_versions_age_check', sql`${table.age} between 18 and 100`),
  check('persona_versions_behavior_check', sql`${table.emotionalLevel} between 1 and 10 and ${table.aggressiveness} between 1 and 10 and ${table.patience} between 1 and 10 and ${table.trustLevel} between 1 and 10 and ${table.curiosityLevel} between 1 and 10`),
  index('persona_versions_submission_idx').on(table.sourceSubmissionId),
  index('persona_versions_branch_idx').on(table.creatorBranchId),
])

export const personaVersionSecrets = pgTable('persona_version_secrets', {
  personaId: varchar('persona_id', { length: 128 }).notNull(),
  version: integer('version').notNull(),
  hiddenInstructions: text('hidden_instructions').notNull().default(''),
  personaKnowledge: text('persona_knowledge').notNull().default(''),
  personaUnknowns: text('persona_unknowns').notNull().default(''),
  updatedBy: varchar('updated_by', { length: 128 }).references(() => users.firebaseUid, { onDelete: 'restrict' }),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, table => [
  primaryKey({ columns: [table.personaId, table.version] }),
  foreignKey({ columns: [table.personaId, table.version], foreignColumns: [personaVersions.personaId, personaVersions.version], name: 'persona_version_secrets_version_fk' }).onDelete('cascade'),
])

export const scenarios = pgTable('scenarios', {
  id: varchar('id', { length: 128 }).primaryKey(),
  personaId: varchar('persona_id', { length: 128 }).references(() => personas.id, { onDelete: 'restrict' }),
  title: varchar('title', { length: 200 }).notNull(),
  description: text('description').notNull(),
  target: text('target').notNull(),
  consumerProfile: text('consumer_profile').notNull(),
  difficulty: text('difficulty').notNull(),
  icon: varchar('icon', { length: 100 }).notNull(),
  customerName: varchar('customer_name', { length: 100 }).notNull(),
  gender: text('gender').notNull(),
  aggressiveness: smallint('aggressiveness').notNull(),
  patience: smallint('patience').notNull(),
  responseStyle: text('response_style').notNull(),
  firstSpeaker: text('first_speaker').notNull(),
  openingMessage: text('opening_message'),
  baseXp: integer('base_xp'),
  status: text('status').notNull().default('draft'),
  createdBy: varchar('created_by', { length: 128 }).references(() => users.firebaseUid, { onDelete: 'restrict' }),
  legacyData: jsonb('legacy_data').$type<Record<string, unknown>>(),
  ...timestamps,
}, table => [
  check('scenarios_id_check', sql`${table.id} ~ '^[a-zA-Z0-9_-]+$'`),
  check('scenarios_difficulty_check', sql`${table.difficulty} in ('Easy', 'Medium', 'Hard')`),
  check('scenarios_gender_check', sql`${table.gender} in ('Pria', 'Wanita')`),
  check('scenarios_behavior_check', sql`${table.aggressiveness} between 1 and 10 and ${table.patience} between 1 and 10`),
  check('scenarios_response_style_check', sql`${table.responseStyle} in ('To the point', 'Banyak Tanya', 'Ragu-ragu', 'Cerewet')`),
  check('scenarios_first_speaker_check', sql`${table.firstSpeaker} in ('AI', 'Sales')`),
  check('scenarios_status_check', sql`${table.status} in ('draft', 'published', 'archived')`),
  check('scenarios_base_xp_check', sql`${table.baseXp} is null or ${table.baseXp} >= 0`),
  index('scenarios_status_updated_idx').on(table.status, table.updatedAt),
  index('scenarios_persona_idx').on(table.personaId),
])

export const scenarioSecrets = pgTable('scenario_secrets', {
  scenarioId: varchar('scenario_id', { length: 128 }).primaryKey().references(() => scenarios.id, { onDelete: 'cascade' }),
  hiddenRules: text('hidden_rules').notNull().default(''),
  updatedBy: varchar('updated_by', { length: 128 }).references(() => users.firebaseUid, { onDelete: 'restrict' }),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
})

export const scenarioSuccessConditions = pgTable('scenario_success_conditions', {
  scenarioId: varchar('scenario_id', { length: 128 }).notNull().references(() => scenarios.id, { onDelete: 'cascade' }),
  position: smallint('position').notNull(),
  condition: text('condition').notNull(),
}, table => [
  primaryKey({ columns: [table.scenarioId, table.position] }),
  check('scenario_success_conditions_position_check', sql`${table.position} >= 0`),
  check('scenario_success_conditions_value_check', sql`length(trim(${table.condition})) > 0`),
])

export const sessions = pgTable('sessions', {
  id: varchar('id', { length: 128 }).primaryKey(),
  userId: varchar('user_id', { length: 128 }).notNull().references(() => users.firebaseUid, { onDelete: 'restrict' }),
  scenarioId: varchar('scenario_id', { length: 128 }).notNull().references(() => scenarios.id, { onDelete: 'restrict' }),
  personaId: varchar('persona_id', { length: 128 }),
  personaVersion: integer('persona_version'),
  salespersonName: varchar('salesperson_name', { length: 100 }).notNull(),
  score: smallint('score').notNull().default(0),
  analysisStatus: text('analysis_status').notNull().default('processing'),
  analysisAttempt: integer('analysis_attempt').notNull().default(1),
  analysisError: text('analysis_error'),
  analysisProvider: varchar('analysis_provider', { length: 100 }),
  transcriptQuality: text('transcript_quality'),
  inputDigest: varchar('input_digest', { length: 64 }),
  scenarioSnapshot: jsonb('scenario_snapshot').$type<Record<string, unknown>>(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  completedAt: timestamp('completed_at', { withTimezone: true }),
}, table => [
  check('sessions_id_check', sql`${table.id} ~ '^[a-zA-Z0-9_-]+$'`),
  check('sessions_score_check', sql`${table.score} between 0 and 100`),
  check('sessions_status_check', sql`${table.analysisStatus} in ('processing', 'completed', 'failed')`),
  check('sessions_attempt_check', sql`${table.analysisAttempt} >= 1`),
  check('sessions_transcript_quality_check', sql`${table.transcriptQuality} is null or ${table.transcriptQuality} in ('partial', 'complete')`),
  check('sessions_persona_pair_check', sql`(${table.personaId} is null) = (${table.personaVersion} is null)`),
  check('sessions_input_digest_check', sql`${table.inputDigest} is null or ${table.inputDigest} ~ '^[0-9a-f]{64}$'`),
  check('sessions_public_snapshot_check', sql`${table.scenarioSnapshot} is null or not (${table.scenarioSnapshot} ?| array['hiddenRules', 'hiddenInstructions', 'personaKnowledge', 'personaUnknowns'])`),
  foreignKey({ columns: [table.personaId, table.personaVersion], foreignColumns: [personaVersions.personaId, personaVersions.version], name: 'sessions_persona_version_fk' }).onDelete('restrict'),
  index('sessions_user_created_idx').on(table.userId, table.createdAt),
  index('sessions_scenario_created_idx').on(table.scenarioId, table.createdAt),
  index('sessions_status_updated_idx').on(table.analysisStatus, table.updatedAt),
  index('sessions_persona_version_idx').on(table.personaId, table.personaVersion),
])

export const sessionTranscriptTurns = pgTable('session_transcript_turns', {
  sessionId: varchar('session_id', { length: 128 }).notNull().references(() => sessions.id, { onDelete: 'cascade' }),
  sequence: integer('sequence').notNull(),
  role: text('role').notNull(),
  text: text('text').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }),
  source: varchar('source', { length: 100 }),
  finalized: boolean('finalized').notNull().default(true),
  confidence: real('confidence'),
}, table => [
  primaryKey({ columns: [table.sessionId, table.sequence] }),
  check('session_transcript_turns_sequence_check', sql`${table.sequence} >= 0`),
  check('session_transcript_turns_role_check', sql`${table.role} in ('user', 'model')`),
  check('session_transcript_turns_text_check', sql`length(${table.text}) between 1 and 5000`),
  check('session_transcript_turns_confidence_check', sql`${table.confidence} is null or ${table.confidence} between 0 and 1`),
])

export const sessionEvaluations = pgTable('session_evaluations', {
  sessionId: varchar('session_id', { length: 128 }).primaryKey().references(() => sessions.id, { onDelete: 'cascade' }),
  evaluationVersion: varchar('evaluation_version', { length: 50 }).notNull(),
  provider: varchar('provider', { length: 100 }),
  overallScore: smallint('overall_score').notNull(),
  grade: varchar('grade', { length: 50 }),
  summary: text('summary'),
  verdict: text('verdict').notNull(),
  strengths: text('strengths').array().notNull().default(sql`ARRAY[]::text[]`),
  weaknesses: text('weaknesses').array().notNull().default(sql`ARRAY[]::text[]`),
  keyObjectionsHandled: text('key_objections_handled').array().notNull().default(sql`ARRAY[]::text[]`),
  missedOpportunities: text('missed_opportunities').array().notNull().default(sql`ARRAY[]::text[]`),
  actionableTips: text('actionable_tips').array().notNull().default(sql`ARRAY[]::text[]`),
  suggestedResponses: text('suggested_responses').array().notNull().default(sql`ARRAY[]::text[]`),
  recommendedNextScenario: text('recommended_next_scenario'),
  actionPlan: text('action_plan').array().notNull().default(sql`ARRAY[]::text[]`),
  skillScores: jsonb('skill_scores').$type<unknown[]>(),
  evaluationDetails: jsonb('evaluation_details').$type<Record<string, unknown>>(),
  rawFeedback: jsonb('raw_feedback').$type<Record<string, unknown>>(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, table => [
  check('session_evaluations_score_check', sql`${table.overallScore} between 0 and 100`),
  index('session_evaluations_score_idx').on(table.overallScore),
  index('session_evaluations_provider_created_idx').on(table.provider, table.createdAt),
])

export const appSettings = pgTable('app_settings', {
  id: text('id').primaryKey().default('global'),
  modelProvider: text('model_provider').notNull().default('gemini'),
  geminiModel: varchar('gemini_model', { length: 200 }),
  ollamaModel: varchar('ollama_model', { length: 200 }),
  openRouterModel: varchar('openrouter_model', { length: 200 }),
  thinkingDelay: integer('thinking_delay').notNull().default(1500),
  frustrationSensitivity: real('frustration_sensitivity').notNull().default(5),
  ollamaUrl: text('ollama_url'),
  nestedConfig: jsonb('nested_config').$type<Record<string, unknown>>(),
  updatedBy: varchar('updated_by', { length: 128 }).references(() => users.firebaseUid, { onDelete: 'restrict' }),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, table => [
  check('app_settings_singleton_check', sql`${table.id} = 'global'`),
  check('app_settings_provider_check', sql`${table.modelProvider} in ('gemini', 'ollama', 'openrouter')`),
  check('app_settings_thinking_delay_check', sql`${table.thinkingDelay} between 0 and 30000`),
  check('app_settings_frustration_check', sql`${table.frustrationSensitivity} between 1 and 10`),
])

export const migrationRecords = pgTable('migration_records', {
  id: bigint('id', { mode: 'number' }).primaryKey().generatedAlwaysAsIdentity(),
  migrationName: varchar('migration_name', { length: 100 }).notNull(),
  sourceCollection: varchar('source_collection', { length: 100 }).notNull(),
  sourceDocumentId: varchar('source_document_id', { length: 256 }).notNull(),
  targetTable: varchar('target_table', { length: 100 }),
  targetKey: jsonb('target_key').$type<Record<string, unknown>>(),
  sourceHash: varchar('source_hash', { length: 64 }),
  status: text('status').notNull().default('pending'),
  attemptCount: integer('attempt_count').notNull().default(0),
  errorCode: varchar('error_code', { length: 100 }),
  errorDetail: text('error_detail'),
  metadata: jsonb('metadata').$type<Record<string, unknown>>(),
  startedAt: timestamp('started_at', { withTimezone: true }),
  migratedAt: timestamp('migrated_at', { withTimezone: true }),
  verifiedAt: timestamp('verified_at', { withTimezone: true }),
  rolledBackAt: timestamp('rolled_back_at', { withTimezone: true }),
}, table => [
  check('migration_records_status_check', sql`${table.status} in ('pending', 'migrated', 'verified', 'failed', 'rolled_back')`),
  check('migration_records_attempt_check', sql`${table.attemptCount} >= 0`),
  uniqueIndex('migration_records_source_unique').on(table.migrationName, table.sourceCollection, table.sourceDocumentId),
  index('migration_records_status_idx').on(table.migrationName, table.status),
])
